language: php
php:
  - 5.6
sudo: required
services:
  - mysql

dist: trusty
before_install: echo 'before install'
before_script:
  - echo 'Before script'
  - pwd
  - ls -a
  - git status
  - mysql -e 'create database IF NOT EXISTS egcajtk_egcdb;' 
  - mysql -u root -e "USE egcajtk_egcdb;"
  - mysql -u root -e "CREATE USER 'egcajtk_egc1617'@'localhost' IDENTIFIED BY 'egcajtk_egc1617';"
  - mysql -u root -e "GRANT ALL ON egcajtk_egcdb.* TO 'egcajtk_egc1617'@'localhost';"
  - mysql -u root -e "show databases;"
  - mysql -u root -e "select * from mysql.user;"
script: phpunit auth/tests/databaseTest.php
after_success:
  - echo 'after success'
  - git remote add production https://{GH_REF}
  - git remote -v
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master > /dev/null 2>&1
after_script: echo 'after script'
